# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171108_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
